version: '3.9'

services:
  web:
    build: ./client/jsxapp
    ports:
      - 3000:3000
    volumes:
      - ./client/jsxapp:/user/src/app
    environment:
    # - NODE_ENV=production
      REACT_APP_API_URL: http://localhost:5000
    depends_on:
      - server

  server:
    build: ./server
    env_file: ./.env
    ports:
      - 80:5000
    environment:
      # - DB_URL=mysql://root:password@localhost:3306/nova_db
      - DB_HOST=db
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
      - CLIENT_ORIGIN=$CLIENT_ORIGIN
    depends_on:
      - db
    volumes:
      - ./server:/app

  db:
    image: mysql/mysql-server:latest
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql 
    networks:
      - server
      - web
    
networks:
  server:
  web:
    
volumes:
  db:
